steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'NEXT_PUBLIC_PUBLISHABLE_KEY=${_NEXT_PUBLIC_PUBLISHABLE_KEY}'
      - 'NEXT_PUBLIC_SECRET_KEY=${_NEXT_PUBLIC_SECRET_KEY}'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'export']