steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--no-cache"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: us-central1
  _LABELS: gcb-trigger-id=0f424f6b-8511-4dc9-96b0-872930c49e74
  _TRIGGER_ID: 0f424f6b-8511-4dc9-96b0-872930c49e74
  _SERVICE_NAME: sprintzero
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sprintzero
