steps:
  - name: node:18.12.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY}"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - "APPLE_KEY_ID=${_APPLE_KEY_ID}"
      - "APPLE_MUSIC_KIT_PRIVATE_KEY=${_APPLE_MUSIC_KIT_PRIVATE_KEY}"
      - "APPLE_TEAM_ID=${_APPLE_TEAM_ID}"
      - "EMAIL_FROM_NO_REPLY=${_EMAIL_FROM_NO_REPLY}"
      - "EMAIL_PASSWORD_NO_REPLY=${_EMAIL_PASSWORD_NO_REPLY}"
      - "NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}"
      - "NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_API_KEY}"
      - "OPENAI_API_KEY=${_OPENAI_API_KEY}"
      - "SPOTIFY_CLIENT_ID=${_SPOTIFY_CLIENT_ID}"
      - "SPOTIFY_CLIENT_SECRET=${_SPOTIFY_CLIENT_SECRET}"
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --cache=true
    id: Build
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
options:
  substitutionOption: ALLOW_LOOSE
  machineType: "E2_HIGHCPU_8"
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _DEPLOY_REGION: us-central1
  _LABELS: gcb-trigger-id=da8dd881-4f33-4bbf-a73c-8b7b4a9ba0b7
  _TRIGGER_ID: da8dd881-4f33-4bbf-a73c-8b7b4a9ba0b7
  _SERVICE_NAME: sprintzero
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sprintzero
  - production
