module.exports = {
	content: [`./src/**/*.{js,ts,jsx,tsx}`],
	darkMode: `class`,
	theme: {
		colors: {
			transparent: `transparent`,
			current: `currentColor`,
			white: `white`,
			black: `black`,

			// Brand colors
			primaryBg: `rgb(var(--color-primary-bg) / <alpha-value>)`,
			primaryBgHover: `rgb(var(--color-primary-bg-hover) / <alpha-value>)`,
			primaryBorder: `rgb(var(--color-primary-border) / <alpha-value>)`,
			primaryBorderHover: `rgb(var(--color-primary-border-hover) / <alpha-value>)`,
			primaryHover: `rgb(var(--color-primary-hover) / <alpha-value>)`,
			primary: `rgb(var(--color-primary) / <alpha-value>)`,
			primaryActive: `rgb(var(--color-primary-active) / <alpha-value>)`,
			primaryTextHover: `rgb(var(--color-primary-text-hover) / <alpha-value>)`,
			primaryText: `rgb(var(--color-primary-text) / <alpha-value>)`,
			primaryTextActive: `rgb(var(--color-primary-text-active) / <alpha-value>)`,

			// Success colors
			successBg: `rgb(var(--color-success-bg) / <alpha-value>)`,
			successBgHover: `rgb(var(--color-success-bg-hover) / <alpha-value>)`,
			successBorder: `rgb(var(--color-success-border) / <alpha-value>)`,
			successBorderHover: `rgb(var(--color-success-border-hover) / <alpha-value>)`,
			successHover: `rgb(var(--color-success-hover) / <alpha-value>)`,
			success: `rgb(var(--color-success) / <alpha-value>)`,
			successActive: `rgb(var(--color-success-active) / <alpha-value>)`,
			successTextHover: `rgb(var(--color-success-text-hover) / <alpha-value>)`,
			successText: `rgb(var(--color-success-text) / <alpha-value>)`,
			successTextActive: `rgb(var(--color-success-text-active) / <alpha-value>)`,

			// Warning colors
			warningBg: `rgb(var(--color-warning-bg) / <alpha-value>)`,
			warningBgHover: `rgb(var(--color-warning-bg-hover) / <alpha-value>)`,
			warningBorder: `rgb(var(--color-warning-border) / <alpha-value>)`,
			warningBorderHover: `rgb(var(--color-warning-border-hover) / <alpha-value>)`,
			warningHover: `rgb(var(--color-warning-hover) / <alpha-value>)`,
			warning: `rgb(var(--color-warning) / <alpha-value>)`,
			warningActive: `rgb(var(--color-warning-active) / <alpha-value>)`,
			warningTextHover: `rgb(var(--color-warning-text-hover) / <alpha-value>)`,
			warningText: `rgb(var(--color-warning-text) / <alpha-value>)`,
			warningTextActive: `rgb(var(--color-warning-text-active) / <alpha-value>)`,

			// Error colors
			errorBg: `rgb(var(--color-error-bg) / <alpha-value>)`,
			errorBgHover: `rgb(var(--color-error-bg-hover) / <alpha-value>)`,
			errorBorder: `rgb(var(--color-error-border) / <alpha-value>)`,
			errorBorderHover: `rgb(var(--color-error-border-hover) / <alpha-value>)`,
			errorHover: `rgb(var(--color-error-hover) / <alpha-value>)`,
			error: `rgb(var(--color-error) / <alpha-value>)`,
			errorActive: `rgb(var(--color-error-active) / <alpha-value>)`,
			errorTextHover: `rgb(var(--color-error-text-hover) / <alpha-value>)`,
			errorText: `rgb(var(--color-error-text) / <alpha-value>)`,
			errorTextActive: `rgb(var(--color-error-text-active) / <alpha-value>)`,

			// Info colors
			infoBg: `rgb(var(--color-info-bg) / <alpha-value>)`,
			infoBgHover: `rgb(var(--color-info-bg-hover) / <alpha-value>)`,
			infoBorder: `rgb(var(--color-info-border) / <alpha-value>)`,
			infoBorderHover: `rgb(var(--color-info-border-hover) / <alpha-value>)`,
			infoHover: `rgb(var(--color-info-hover) / <alpha-value>)`,
			info: `rgb(var(--color-info) / <alpha-value>)`,
			infoActive: `rgb(var(--color-info-active) / <alpha-value>)`,
			infoTextHover: `rgb(var(--color-info-text-hover) / <alpha-value>)`,
			infoText: `rgb(var(--color-info-text) / <alpha-value>)`,
			infoTextActive: `rgb(var(--color-info-text-active) / <alpha-value>)`,

			// Neutral colors
			text: `var(--color-text)`,
			textSecondary: `var(--color-text-secondary)`,
			textTertiary: `var(--color-text-tertiary)`,
			textQuaternary: `var(--color-text-quaternary)`,
			border: `rgb(var(--color-border) / <alpha-value>)`,
			borderSecondary: `rgb(var(--color-border-secondary) / <alpha-value>)`,
			fill: `var(--color-fill)`,
			fillSecondary: `var(--color-fill-secondary)`,
			fillTertiary: `var(--color-fill-tertiary)`,
			fillQuaternary: `var(--color-fill-quaternary)`,
			bgContainer: `rgb(var(--color-bg-container) / <alpha-value>)`,
			bgElevated: `rgb(var(--color-bg-elevated) / <alpha-value>)`,
			bgLayout: `rgb(var(--color-bg-layout) / <alpha-value>)`,
			bgSpotlight: `var(--color-bg-spotlight)`,
			bgMask: `var(--color-bg-mask)`,
		},
		flex: {
			1: `1 1 0px`,
		},
		fontFamily: {
			mono: [`monospace`],
		},
		fontSize: {
			xs: `0.625rem`,
			sm: `0.75rem`,
			base: `0.875rem`,
			lg: `1rem`,
			xl: `1.25rem`,
			"2xl": `1.5rem`,
			"3xl": `1.875rem`,
			"4xl": `2.25rem`,
			"5xl": `3rem`,
			"6xl": `3.75rem`,
			"7xl": `4.5rem`,
			"8xl": `6rem`,
			"9xl": `8rem`,
		},
	},
}
