import Head from 'next/head'
import Plans from '../components/Plans'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Sprint Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Plans />
    </div>
  )
}
