import React, {useEffect, useState} from "react";
import Head from "next/head";
import Billing from "../components/Billing";
import Layout from "../components/Layout";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import axios from "axios";
import { useRecoilValue } from "recoil";
import { selectedPlanState } from "../atoms/planAtom";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_PUBLISHABLE_KEY);

const getCountries = async () => {
  const res = await axios.get(
    "https://countriesnow.space/api/v0.1/countries/iso"
  );
  return res.data.data;
};

const getIp = async () => {
  const res = await axios.get("https://geolocation-db.com/json/");
  return res.data;
};

const Payment = () => {
  const [countries, setCountries] = useState(null);
  const [ip, setIp] = useState(null);
  const selectedPlan = useRecoilValue(selectedPlanState);

  useEffect(() => {
    (async () => {
      const countries = await getCountries();
      const ip = await getIp();
      setCountries(countries);
      setIp(ip.IPv4);
    })();
  }, [])

  return (
    <div>
      <Head>
        <title>Payment | Sprint Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Elements stripe={stripePromise}>
          {countries && ip && (
            <Billing
              selectedPlan={selectedPlan}
              countries={countries}
              ip={ip}
            />
          )}
        </Elements>
      </Layout>
    </div>
  );
};

export default Payment;