import Head from "next/head";
import { useRouter } from "next/router";

export default function payment() {
  const router = useRouter();
  const { plan } = router.query;
  return (
    <div>
      <Head>
        <title>Payment | Sprint Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {plan}
    </div>
  );
}
