import React from 'react'
import Head from "next/head";
import Billing from '../../components/Billing';
import Layout from '../../components/Layout'
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_PUBLISHABLE_KEY);


const payment = ({selectedPlan, countries}) => {
  return (
    <div>
      <Head>
        <title>Payment | Sprint Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Elements stripe={stripePromise}>
          <Billing selectedPlan={selectedPlan} countries={countries.data} />
        </Elements>
      </Layout>
    </div>
  );
}

export default payment

export const getServerSideProps = async (context) => {
  const plan = context.params.plan;

  let selectedPlan;

  if (plan === "basic") {
    selectedPlan = "Basic"
  } else if (plan === "professional") {
    selectedPlan = "Professional";
  } else {
    selectedPlan = "invalid"
  }

  const res = await fetch("https://countriesnow.space/api/v0.1/countries/iso");

  const countries = await res.json();

  if (selectedPlan === "invalid") {
    return {
      notFound: true,
    };
  }


  return {
    props: {
      selectedPlan, countries
    },
  };
};
