import React from 'react'
import Head from "next/head";
import Billing from '../../components/Billing';
import Layout from '../../components/Layout'

const payment = ({selectedPlan, countries}) => {
  return (
    <div>
      <Head>
        <title>Payment | Sprint Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Billing selectedPlan={selectedPlan} countries={countries.data} />
      </Layout>
    </div>
  );
}

export default payment

export const getServerSideProps = async (context) => {
  const plan = context.params.plan;

  let selectedPlan;

  if (plan === "basic") {
    selectedPlan = {plan: "Basic", price: 9.99}
  } else if (plan === "professional") {
    selectedPlan = { plan: "Professional", price: 99.99 };
  } else {
    selectedPlan = "invalid"
  }

  const res = await fetch(
    "https://countriesnow.space/api/v0.1/countries/positions"
  );

  const countries = await res.json();

  if (selectedPlan === "invalid") {
    return {
      notFound: true,
    };
  }


  return {
    props: {
      selectedPlan, countries
    },
  };
};
