on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: sprintzero.azurecr.io
            username: sprintzero
            password: "S78lwpcP+xiPh/rtWzCNXv04hNh0iIyb"
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sprintzero:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sprintzero:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: "SprintZeroDev"
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sprintzero:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: sprintzero
            registry-password: "S78lwpcP+xiPh/rtWzCNXv04hNh0iIyb"
            name: sprintzero
            location: 'central us'
